include: package:lints/recommended.yaml

plugins:
  more_visibility:
    path: ../

analyzer:
  errors:
    # Treat visibility violations as errors (default)
    more_visibility_protected: error
    more_visibility_module_default: error
