plugins:
  more_visibility:
    path: ../
    diagnostics:
      directory_private: true
      more_visibility_protected: true
      more_visibility_module_default: true
analyzer:
  errors:
    directory_private: error
    more_visibility_protected: error
    more_visibility_module_default: error
